### ISSUE TITLE
OSError: -530 using the pheripheral role on esp32-c3

### ISSUE THREAD

**Issue by BOB63** [kevinmcaleer/pi_to_pico_bluetooth#1]
Hi Kevin,
starting the code pico_a.py of lesson 1 as Pheripheral role on a ESP32-c3 I got the error code -530 and seems to be generated by the line 115 (  services=[BLE_SVC_UUID], ) inside this while cycle:
```
while True:
        async with await aioble.advertise(
            BLE_ADVERTISING_INTERVAL,
            name="LE_NAME",
            services=[BLE_SVC_UUID],
            appearance=BLE_APPEARANCE) as connection:
            print(f"{BLE_NAME} connected to another device: {connection.device}")

            tasks = [
                asyncio.create_task(send_data_task(connection, characteristic)),
            ]
            await asyncio.gather(*tasks)
            print(f"{IAM} disconnected")
            break


```
here the complete errore log : 

MPY: soft reboot
Peripheral starting to advertise
Traceback (most recent call last):
  File "<stdin>", line 198, in <module>
  File "asyncio/core.py", line 1, in run
  File "asyncio/core.py", line 1, in run_until_complete
  File "asyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 196, in main
  File "asyncio/funcs.py", line 1, in gather
  File "asyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 115, in run_peripheral_mode
  File "/lib/aioble/peripheral.py", line 158, in advertise
OSError: -530

In google I'm not able to understand what means error -530 .

tks Roberto.

**Comment by sentairanger** [comment]
So I did a little digging and the error points to a "connection time out" or "ble controller issue". Seems that there should be a delay to prevent a timeout.
